#!/usr/bin/env bash
# prints nine "Best school" on the screen or Hi in 9
i=0
while [ "$i" -lt 10 ]
do
 if [ "$i" -eq 3 ]
 then
   echo "bad luck"
 elif [ "$i" -eq 7 ]
 then
   echo "good luck"
 elif [ "$i" -lt 10 ]
 then
  echo "Best School"
 fi
 ((i = i + 1))
done
